version: 2.1

jobs:
  test:
    macos:
      xcode: 13.2.1 # Using 13.2.1 to support backwards compatibility of Modern Concurrency
    steps:
      - checkout
      - run:
          name: Install Typesense
          command: |
            curl --output ts.tar.gz  https://dl.typesense.org/releases/0.22.2/typesense-server-0.22.2-darwin-amd64.tar.gz
            tar -xzf ts.tar.gz
      - run:
          name: Run Typesense
          background: true
          command: |
            ./typesense-server --api-key=xyz --data-dir=/tmp
      - run:
          # Build and Test the Typesense Package
          name: Run Tests
          command: swift test

workflows:
  version: 2
  test_build:
    jobs:
      - test
