version: 2.1

jobs:
  test:
    macos:
      xcode: 13.2.1 # Using 13.2.1 to support backwards compatibility of Modern Concurrency
    steps:
      - checkout
      - run:
          name: Install docker
          command: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
      - run:
          name: Docker hello-world
          command: |
            docker run hello-world
      - run:
          # Build and Test the Typesense Package
          name: Run Tests
          command: swift test

workflows:
  version: 2
  test_build:
    jobs:
      - test
