name: Build and Test

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-11
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          brew install docker

      - name: Run Typesense
        run: |
          mkdir $(pwd)/typesense-data
          docker run -p 8108:8108 \
            -d \
            -v$(pwd)/typesense-data:/data typesense/typesense:0.25.2 \
            --data-dir /data \
            --api-key=xyz \
            --enable-cors
        shell: bash

      - name: Set up Xcode 13.2.1
        uses: maxim-lobanov/setup-xcode@v1.2.1
        with:
          xcode-version: '13.2.1'

      - name: Run Tests
        run: swift test
