name: Build and Test

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-11
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Typesense
        run: |
          curl --output ts.tar.gz  https://dl.typesense.org/releases/0.25.2/typesense-server-0.25.2-darwin-amd64.tar.gz
          tar -xzf ts.tar.gz

      - name: Run Typesense
        run: |
          ./typesense-server --api-key=xyz --data-dir=/tmp &
        shell: bash

      - name: Set up Xcode 13.2.1
        uses: maxim-lobanov/setup-xcode@v1.2.1
        with:
          xcode-version: '13.2.1'

      - name: Run Tests
        run: swift test
